[package]
name = "codet"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.14.0", features = ["svg", "image", "tokio"] }
iced_highlighter = "0.14.0"
rfd = "0.15"
portable-pty = "0.8"
strip-ansi-escapes = "0.2"
syntect = { version = "5", default-features = false, features = ["default-syntaxes", "default-themes", "regex-fancy", "html"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }

[package.metadata.bundle]
name = "Codet"
identifier = "com.noelpinto.codet"
icon = ["assets/icon.icns"]
category = "Developer Tool"
